name: Garmin Data Sync

on:
  schedule:
    - cron: '0 0 * * 1' # 毎週月曜 AM9:00 (JST) ※UTC 0:00
  workflow_dispatch: # 手動実行ボタンも追加

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: pip install garminconnect
        
      - name: Run script
        env:
          GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
        run: python main.py
        
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.json
          git commit -m "Add latest Garmin data" || exit 0
          git push
